# Generated by Django 4.2.16 on 2024-10-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
