# Generated by Django 4.2.16 on 2024-10-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationapp', '0002_alter_destination_district_alter_destination_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='Destination_img',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
    ]
